application: andrews
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: media/css
  
- url: /js
  static_dir: media/js

- url: /imgs
  static_dir: media/imgs
  
- url: /.*
  script: main.py
  

